package com.hnzs.dao;

import org.apache.ibatis.annotations.Param;

import com.hnzs.bean.Admin;

public interface AdminMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated
	 */
	int insert(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated
	 */
	int insertSelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated
	 */
	Admin selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Admin record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table admin
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Admin record);

	/****
	 * 根据管理员账号密码登陆
	 * 
	 * @param ad_name
	 *            管理员账号
	 * @param ad_pwd
	 *            管理员密码
	 * @return 登陆实体
	 */
	Admin selectBynameApwd(@Param("ad_name") String ad_name, @Param("ad_pwd") String ad_pwd);
}