package com.hnzs.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.hnzs.bean.Opinion;

public interface OpinionMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table opinion
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table opinion
	 *
	 * @mbggenerated
	 */
	int insert(Opinion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table opinion
	 *
	 * @mbggenerated
	 */
	int insertSelective(Opinion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table opinion
	 *
	 * @mbggenerated
	 */
	Opinion selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table opinion
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(Opinion record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table opinion
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Opinion record);

	/**
	 * 查询总数
	 * 
	 * @return
	 */
	Integer findOpinCount();

	/***
	 * 
	 * @return
	 */
	List<Opinion> findOPinDate(@Param("start") Integer start, @Param("size") Integer size);

}