package com.hnzs.dao;

import com.hnzs.bean.VoteLog;

public interface VoteLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_log
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_log
     *
     * @mbggenerated
     */
    int insert(VoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_log
     *
     * @mbggenerated
     */
    int insertSelective(VoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_log
     *
     * @mbggenerated
     */
    VoteLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(VoteLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table vote_log
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(VoteLog record);
}