package com.hnzs.dao;

import org.apache.ibatis.annotations.Param;

import com.hnzs.bean.VoteNexus;

public interface VoteNexusMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table vote_nexus
	 *
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table vote_nexus
	 *
	 * @mbggenerated
	 */
	int insert(VoteNexus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table vote_nexus
	 *
	 * @mbggenerated
	 */
	int insertSelective(VoteNexus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table vote_nexus
	 *
	 * @mbggenerated
	 */
	VoteNexus selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table vote_nexus
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKeySelective(VoteNexus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table vote_nexus
	 *
	 * @mbggenerated
	 */
	int updateByPrimaryKey(VoteNexus record);

	/***
	 * 根据用户id和得票id删除关联
	 * 
	 * @param vote_id
	 *            投票者id
	 * @param voted_id
	 *            得票者id
	 * @return
	 */
	int deleteByVE(@Param("vote_id") Integer vote_id, @Param("voted_id") Integer voted_id);

	/***
	 * 重要!清空所有数据
	 * 
	 * @return
	 */
	Integer deleteByAll();
}