package com.hnzs.bean;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class Employee {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column employee.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column employee.emp_name
	 *
	 * @mbggenerated
	 */
	private String empName;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column employee.emp_pwd
	 *
	 * @mbggenerated
	 */
	private String empPwd;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column employee.emp_img
	 *
	 * @mbggenerated
	 */
	private String empImg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column employee.emp_vote_num
	 *
	 * @mbggenerated
	 */
	private Integer empVoteNum;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column employee.init_time
	 *
	 * @mbggenerated
	 */
	private Date initTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column employee.id
	 *
	 * @return the value of employee.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column employee.id
	 *
	 * @param id
	 *            the value for employee.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column employee.emp_name
	 *
	 * @return the value of employee.emp_name
	 *
	 * @mbggenerated
	 */
	public String getEmpName() {
		return empName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column employee.emp_name
	 *
	 * @param empName
	 *            the value for employee.emp_name
	 *
	 * @mbggenerated
	 */
	public void setEmpName(String empName) {
		this.empName = empName == null ? null : empName.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column employee.emp_pwd
	 *
	 * @return the value of employee.emp_pwd
	 *
	 * @mbggenerated
	 */
	public String getEmpPwd() {
		return empPwd;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column employee.emp_pwd
	 *
	 * @param empPwd
	 *            the value for employee.emp_pwd
	 *
	 * @mbggenerated
	 */
	public void setEmpPwd(String empPwd) {
		this.empPwd = empPwd == null ? null : empPwd.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column employee.emp_img
	 *
	 * @return the value of employee.emp_img
	 *
	 * @mbggenerated
	 */
	public String getEmpImg() {
		return empImg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column employee.emp_img
	 *
	 * @param empImg
	 *            the value for employee.emp_img
	 *
	 * @mbggenerated
	 */
	public void setEmpImg(String empImg) {
		this.empImg = empImg == null ? null : empImg.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column employee.emp_vote_num
	 *
	 * @return the value of employee.emp_vote_num
	 *
	 * @mbggenerated
	 */
	public Integer getEmpVoteNum() {
		return empVoteNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column employee.emp_vote_num
	 *
	 * @param empVoteNum
	 *            the value for employee.emp_vote_num
	 *
	 * @mbggenerated
	 */
	public void setEmpVoteNum(Integer empVoteNum) {
		this.empVoteNum = empVoteNum;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column employee.init_time
	 *
	 * @return the value of employee.init_time
	 *
	 * @mbggenerated
	 */
	public Date getInitTime() {
		return initTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column employee.init_time
	 *
	 * @param initTime
	 *            the value for employee.init_time
	 *
	 * @mbggenerated
	 */
	public void setInitTime(Date initTime) {
		this.initTime = initTime;
	}

	/***************************************************/

	/****
	 * 已经获得的投票数
	 */
	private Integer votedNum;

	public Integer getVotedNum() {
		return votedNum;
	}

	public void setVotedNum(Integer votedNum) {
		this.votedNum = votedNum;
	}

	/***
	 * 员工投出的票
	 */
	private List<Employee> votedEmpList = new ArrayList<Employee>();

	public List<Employee> getVotedEmpList() {
		return votedEmpList;
	}

	public void setVotedEmpList(List<Employee> votedEmpList) {
		this.votedEmpList = votedEmpList;
	}

	/**
	 * 传参数的构造方法
	 * 
	 * @param empName
	 * @param empImg
	 */
	public Employee(String empName, String empImg) {
		super();
		this.empName = empName;
		this.empImg = empImg;
	}

	public Employee() {
		super();
		// TODO Auto-generated constructor stub
	}

	@Override
	public String toString() {
		return "Employee [id=" + id + ", empName=" + empName + ", empPwd=" + empPwd + ", empImg=" + empImg
				+ ", empVoteNum=" + empVoteNum + ", initTime=" + initTime + ", votedNum=" + votedNum + ", votedEmpList="
				+ votedEmpList + "]";
	}

}