package com.hnzs.bean;

import java.util.Date;

public class Opinion {

	/***
	 * 提问的员工姓名
	 */
	private String empName;

	/***
	 * 获取状态 读取状态，0未读，1已读
	 */
	private Integer reStat;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column opinion.id
	 *
	 * @mbggenerated
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column opinion.opinion_str
	 *
	 * @mbggenerated
	 */
	private String opinionStr;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column opinion.emp_id
	 *
	 * @mbggenerated
	 */
	private Integer empId;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column opinion.init_time
	 *
	 * @mbggenerated
	 */
	private Date initTime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column opinion.id
	 *
	 * @return the value of opinion.id
	 *
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column opinion.id
	 *
	 * @param id
	 *            the value for opinion.id
	 *
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column opinion.opinion_str
	 *
	 * @return the value of opinion.opinion_str
	 *
	 * @mbggenerated
	 */
	public String getOpinionStr() {
		return opinionStr;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column opinion.opinion_str
	 *
	 * @param opinionStr
	 *            the value for opinion.opinion_str
	 *
	 * @mbggenerated
	 */
	public void setOpinionStr(String opinionStr) {
		this.opinionStr = opinionStr == null ? null : opinionStr.trim();
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column opinion.emp_id
	 *
	 * @return the value of opinion.emp_id
	 *
	 * @mbggenerated
	 */
	public Integer getEmpId() {
		return empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column opinion.emp_id
	 *
	 * @param empId
	 *            the value for opinion.emp_id
	 *
	 * @mbggenerated
	 */
	public void setEmpId(Integer empId) {
		this.empId = empId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column opinion.init_time
	 *
	 * @return the value of opinion.init_time
	 *
	 * @mbggenerated
	 */
	public Date getInitTime() {
		return initTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column opinion.init_time
	 *
	 * @param initTime
	 *            the value for opinion.init_time
	 *
	 * @mbggenerated
	 */
	public void setInitTime(Date initTime) {
		this.initTime = initTime;
	}

	public Integer getReStat() {
		return reStat;
	}

	public void setReStat(Integer reStat) {
		this.reStat = reStat;
	}

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}

}