package com.hnzs.bean;

import java.util.Date;

public class VoteLog {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_log.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_log.emp_id
     *
     * @mbggenerated
     */
    private Integer empId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_log.emp_votenum
     *
     * @mbggenerated
     */
    private Integer empVotenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_log.log_year
     *
     * @mbggenerated
     */
    private Integer logYear;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_log.log_month
     *
     * @mbggenerated
     */
    private Integer logMonth;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_log.init_time
     *
     * @mbggenerated
     */
    private Date initTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_log.id
     *
     * @return the value of vote_log.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_log.id
     *
     * @param id the value for vote_log.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_log.emp_id
     *
     * @return the value of vote_log.emp_id
     *
     * @mbggenerated
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_log.emp_id
     *
     * @param empId the value for vote_log.emp_id
     *
     * @mbggenerated
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_log.emp_votenum
     *
     * @return the value of vote_log.emp_votenum
     *
     * @mbggenerated
     */
    public Integer getEmpVotenum() {
        return empVotenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_log.emp_votenum
     *
     * @param empVotenum the value for vote_log.emp_votenum
     *
     * @mbggenerated
     */
    public void setEmpVotenum(Integer empVotenum) {
        this.empVotenum = empVotenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_log.log_year
     *
     * @return the value of vote_log.log_year
     *
     * @mbggenerated
     */
    public Integer getLogYear() {
        return logYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_log.log_year
     *
     * @param logYear the value for vote_log.log_year
     *
     * @mbggenerated
     */
    public void setLogYear(Integer logYear) {
        this.logYear = logYear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_log.log_month
     *
     * @return the value of vote_log.log_month
     *
     * @mbggenerated
     */
    public Integer getLogMonth() {
        return logMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_log.log_month
     *
     * @param logMonth the value for vote_log.log_month
     *
     * @mbggenerated
     */
    public void setLogMonth(Integer logMonth) {
        this.logMonth = logMonth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_log.init_time
     *
     * @return the value of vote_log.init_time
     *
     * @mbggenerated
     */
    public Date getInitTime() {
        return initTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_log.init_time
     *
     * @param initTime the value for vote_log.init_time
     *
     * @mbggenerated
     */
    public void setInitTime(Date initTime) {
        this.initTime = initTime;
    }
}