package com.hnzs.bean;

import java.util.Date;

public class VoteNexus {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_nexus.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_nexus.vote_id
     *
     * @mbggenerated
     */
    private Integer voteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_nexus.voted_id
     *
     * @mbggenerated
     */
    private Integer votedId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column vote_nexus.init_time
     *
     * @mbggenerated
     */
    private Date initTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_nexus.id
     *
     * @return the value of vote_nexus.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_nexus.id
     *
     * @param id the value for vote_nexus.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_nexus.vote_id
     *
     * @return the value of vote_nexus.vote_id
     *
     * @mbggenerated
     */
    public Integer getVoteId() {
        return voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_nexus.vote_id
     *
     * @param voteId the value for vote_nexus.vote_id
     *
     * @mbggenerated
     */
    public void setVoteId(Integer voteId) {
        this.voteId = voteId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_nexus.voted_id
     *
     * @return the value of vote_nexus.voted_id
     *
     * @mbggenerated
     */
    public Integer getVotedId() {
        return votedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_nexus.voted_id
     *
     * @param votedId the value for vote_nexus.voted_id
     *
     * @mbggenerated
     */
    public void setVotedId(Integer votedId) {
        this.votedId = votedId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column vote_nexus.init_time
     *
     * @return the value of vote_nexus.init_time
     *
     * @mbggenerated
     */
    public Date getInitTime() {
        return initTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column vote_nexus.init_time
     *
     * @param initTime the value for vote_nexus.init_time
     *
     * @mbggenerated
     */
    public void setInitTime(Date initTime) {
        this.initTime = initTime;
    }
}